### ISSUE TITLE
inconsistent version warning due to scikit-learn and model pickling

### ISSUE THREAD

**Issue by zivy** [niaid/tbp-cxr-outlier#43]
With the compatibility option scikit-learn~=1.3.0 set in the requirements.txt, when the package is installed into a clean python environment on OSX,
```
python -m pip install tbpcxr-0.5.1-py3-none-any.whl
```
the scikit-learn version installed is 1.3.2 which is compatible with 1.3.0.

When the prediction model is loaded:
```
from tbpcxr.model import Model
outlier_model = Model.load_outlier_pcamodel()
```
The following pickle related warning is issued:
```
path_to_anaconda/anaconda3/envs/cxr_outlier/lib/python3.11/site-packages/sklearn/base.py:348: InconsistentVersionWarning: Trying to unpickle estimator PCA from version 1.3.0 when using version 1.3.2. This might lead to breaking code or invalid results. Use at your own risk. For more info please refer to:
https://scikit-learn.org/stable/model_persistence.html#security-maintainability-limitations
```

Note that the model does work correctly (random non CXR classified as outlier, CXR as inlier), so the warning can be ignored, but likely better to address it by pinning the version to 1.3.0.

**Comment by blowekamp** [comment]
That version restriction is rather disappointing. It appears all formats requires "save environment as training": https://scikit-learn.org/stable/model_persistence.html
